name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          ./build.sh

      # Step 4: Run tests on Docker image
      - name: Run tests
        run: |
          ./test.sh

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ./deploy.sh
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ec2-user  # The default user for Amazon Linux 1
          EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}
